services:
  postgres:
    image: postgres:17
    container_name: tutorflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: tutorflow
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tutorflow

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: